FROM ruby:3.2.1

ENV APP_HOME="/app_home"
WORKDIR $APP_HOME
#ENV BUNDLE_PATH="${APP_HOME}/vendor/bundle"

RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash - && apt-get install -y nodejs
RUN npm install --global npm@9.6.1
RUN npm install --global yarn


EXPOSE 3000

CMD ["yarn", "build:css", "--watch"]
